on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing and build
    steps:
      - uses: actions/checkout@v2
      - uses: up9cloud/action-rsync@master
        name: |
          Mode: push, local (SOURCE) to remote (TARGET), run scripts on remote (TARGET)
        env:
          HOST: ${{secrets.DEPLOY_HOST}}
          KEY: ${{secrets.DEPLOY_SSH_KEY}}
          TARGET: /tmp/action-rsync_push/
          VERBOSE: true
          PRE_SCRIPT: |
            echo I ❤️ this action!
            rm -fr /tmp/action-rsync_push
            date -u
          POST_SCRIPT: "ls /tmp/action-rsync_push && date -u"
      - uses: up9cloud/action-rsync@master
        name: |
          Mode: push, local (SOURCE) to remote (TARGET), run scripts at local (SOURCE)
        env:
          HOST: ${{secrets.DEPLOY_HOST}}
          KEY: ${{secrets.DEPLOY_SSH_KEY}}
          TARGET: /tmp/action-rsync/
          VERBOSE: true
          RUN_SCRIPT_ON: local
          PRE_SCRIPT: |
            if ls /tmp/action-rsync; then
              exit 2
            fi
            date -u
          POST_SCRIPT: "if ls /tmp/action-rsync; then exit 2; fi && date -u"
      - uses: up9cloud/action-rsync@master
        name: |
          Mode: pull, remote (SOURCE) to local (TARGET), run scripts at local (TARGET)
        env:
          MODE: pull
          HOST: ${{secrets.DEPLOY_HOST}}
          KEY: ${{secrets.DEPLOY_SSH_KEY}}
          SOURCE: /root/.profile
          TARGET: /tmp/.profile
          VERBOSE: true
          PRE_SCRIPT: |
            if ls /tmp/.profile; then
              exit 2
            fi
            date -u
          POST_SCRIPT: "cat /tmp/.profile && date -u"
      - uses: up9cloud/action-rsync@master
        name: |
          Mode: pull, remote (SOURCE) to local (TARGET), run scripts on remote (SOURCE)
        env:
          MODE: pull
          HOST: ${{secrets.DEPLOY_HOST}}
          KEY: ${{secrets.DEPLOY_SSH_KEY}}
          SOURCE: /root/.profile
          TARGET: /tmp/.profile
          VERBOSE: true
          RUN_SCRIPT_ON: source
          PRE_SCRIPT: |
            rm -fr /tmp/action-rsync_pull
            date -u
          POST_SCRIPT: "if ls /tmp/action-rsync_pull; then exit 2; fi && date -u"
      - uses: up9cloud/action-rsync@master
        name: |
          Mode: local, local (SOURCE) to local (TARGET), run scripts at local (always)
        env:
          MODE: local
          TARGET: /tmp/action-rsync_local/
          VERBOSE: true
          PRE_SCRIPT: |
            if ls /tmp/action-rsync_local; then
              exit 2
            fi
            date -u
          POST_SCRIPT: "ls /tmp/action-rsync_local && date -u"
      - uses: up9cloud/action-rsync@master
        name: |
          Mode: push, local (SOURCE) to remote (TARGET), ssh login by PASSWORD
        env:
          HOST: ${{secrets.DEPLOY_HOST}}
          USER: ${{secrets.DEPLOY_USER}}
          PASSWORD: ${{secrets.DEPLOY_SSH_PASSWORD}}
          SOURCE: /root/.profile
          TARGET: /tmp/.profile
          VERBOSE: true
          PRE_SCRIPT: |
            date -u
          POST_SCRIPT: "pwd && date -u"
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        if: ${{ github.event_name == 'push' && success() }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: sstc/action-rsync
          tag_with_ref: true
      - name: Notify telegram
        uses: up9cloud/action-notify@master
        if: cancelled() == false
        env:
          GITHUB_JOB_STATUS: ${{ job.status }}
          TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
          TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}
